server:
  port: 9081
spring:
  datasource:
    url: jdbc:mysql://localhost:3309/eazybytes
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect


